apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: futbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.12.5
          ports:
            - containerPort: 6333
            - containerPort: 6334
          volumeMounts:
            - name: data
              mountPath: /qdrant/storage
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: qdrant-data
